services:
  # ==========================================
  # 1. BANCO DE DADOS (PostgreSQL)
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: open_autonomous_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - rede_monitoramento

  # ==========================================
  # 2. BACKEND (Spring Boot)
  # ==========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: open_autonomous_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - rede_monitoramento

  # ==========================================
  # 3. FRONTEND (Next.js)
  # ==========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: open_autonomous_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    
    depends_on:
      - backend
    networks:
      - rede_monitoramento

  # ==========================================
  # 4. AGENTE DE IA (Python)
  # ==========================================
  ia-csirt-agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: ia_monitor_agent
    restart: unless-stopped
    networks:
      - rede_monitoramento
    ports:
      - "${PORT_LISTEN}:${PORT_LISTEN}/udp"
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./agent:/app
    env_file:
      - .env
    depends_on:
      - backend
      - postgres

# ==========================================
# CONFIGURAÇÕES DE REDE E VOLUMES
# ==========================================
networks:
  rede_monitoramento:
    name: open-autonomous-threat-detection
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  db:
    name: db