services:
  # ==========================================
  # 1. BANCO DE DADOS (PostgreSQL)
  # ==========================================
  postgres:
    image: postgres:16-alpine
    container_name: open_autonomous_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_monitoramento

  # ==========================================
  # 2. BACKEND (Spring Boot)
  # ==========================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: open_autonomous_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Sobrescreve o localhost para o nome do container do banco na rede Docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - rede_monitoramento

  # ==========================================
  # 3. FRONTEND (Next.js)
  # ==========================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: open_autonomous_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # URL que o browser usará para acessar a API (neste caso, localhost da máquina host)
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
    depends_on:
      - backend
    networks:
      - rede_monitoramento

  # ==========================================
  # 4. AGENTE DE IA (Python)
  # ==========================================
  ia-csirt-agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: ia_monitor_agent
    stdin_open: true
    tty: true
    ports:
      - "5140:5140/udp"
    volumes:
      - ./agent:/app
    environment:
      - PYTHONUNBUFFERED=1
      # Sobrescreve as configs do .env do agente para usar a rede do Docker
      - DB_HOST=postgres 
      - API_ENDPOINT=http://backend:8080/api/v1/events
    depends_on:
      - backend
      - postgres
    restart: unless-stopped
    networks:
      rede_monitoramento:
        ipv4_address: 172.25.0.50

# ==========================================
# CONFIGURAÇÕES DE REDE E VOLUMES
# ==========================================
networks:
  rede_monitoramento:
    name: open-autonomous-threat-detection
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  postgres_data:
    name: db